// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR2qU2JoxrpK8fu2NyJ64Lj-53Ohj6p9I',
    appId: '1:302074327737:web:e13effb021ccb263da2168',
    messagingSenderId: '302074327737',
    projectId: 'rent-5a496',
    authDomain: 'rent-5a496.firebaseapp.com',
    storageBucket: 'rent-5a496.firebasestorage.app',
    measurementId: 'G-Z0PHEPPFJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATNrTZ80Ct6Bww5Uwq3GKsa49qCcpKGc4',
    appId: '1:302074327737:android:b4dce952368f6915da2168',
    messagingSenderId: '302074327737',
    projectId: 'rent-5a496',
    storageBucket: 'rent-5a496.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1QikvssXEQQWNg1aRE4ftgzCsHjT7YNk',
    appId: '1:302074327737:ios:944619e146babb43da2168',
    messagingSenderId: '302074327737',
    projectId: 'rent-5a496',
    storageBucket: 'rent-5a496.firebasestorage.app',
    iosClientId: '302074327737-hgk22a187coc5bch4940v5pv5bvdfl60.apps.googleusercontent.com',
    iosBundleId: 'com.rentalmgr.mobileTenant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR2qU2JoxrpK8fu2NyJ64Lj-53Ohj6p9I',
    appId: '1:302074327737:web:f822cf4d0d08f29cda2168',
    messagingSenderId: '302074327737',
    projectId: 'rent-5a496',
    authDomain: 'rent-5a496.firebaseapp.com',
    storageBucket: 'rent-5a496.firebasestorage.app',
    measurementId: 'G-Q8E25ZZXBT',
  );
}
